DELETE FROM categories;

INSERT INTO categories VALUES(1,1,'Σώμα', 'body');
INSERT INTO categories VALUES(2,1,'Ζώα', 'animals');
INSERT INTO categories VALUES(3,1,'Φρούτα', 'fruits');
INSERT INTO categories VALUES(4,1,'Αντικείμενα', 'object');
INSERT INTO categories VALUES(5,1,'Χρώματα', 'color');
INSERT INTO categories VALUES(6,1,'Σχήματα', 'shape');
INSERT INTO categories VALUES(7,1,'Επαγγέλματα', 'professions');
INSERT INTO categories VALUES(8,1,'Ηλεκτρικές Συσκευές', 'appliancies');
INSERT INTO categories VALUES(9,1,'Τοποθεσία', 'location');
INSERT INTO categories VALUES(10,1,'Οχήματα', 'car');
INSERT INTO categories VALUES(11,1,'Ενέργειες', 'action');
INSERT INTO categories VALUES(12,1,'Συναισθήματα', 'emotion');
INSERT INTO categories VALUES(13,1,'Εποχές', 'season');
INSERT INTO categories VALUES(14,1,'Μήνες', 'month');
INSERT INTO categories VALUES(15,1,'Μέρες Της Εβδομάδας', 'week');
INSERT INTO categories VALUES(16,1,'Αντιθετικοί Προσδιορισμοί', 'opposites');
INSERT INTO categories VALUES(17,1,'Αφαιρετική Ικανότητα', 'substractiveAbillity');
INSERT INTO categories VALUES(18,1,'Αυτοματοποιημένες Πράξεις', 'automatedActions');
INSERT INTO categories VALUES(19,1,'Ερωτήσεις Κλειστού Τύπου', 'closedQuestions');
INSERT INTO categories VALUES(20,1,'Εντοπισμός', 'detect');
INSERT INTO categories VALUES(35,2,'Ορισμοί', 'katonomasiaDefinition');
INSERT INTO categories VALUES(36,2,'Συμπλήρωση προτάσεων', 'katonomasiaCompleteSentence');
INSERT INTO categories VALUES(37,2,'Ήχοι', 'katonomasiaSounds');
INSERT INTO categories VALUES(38,3,'Αντικείμενα', 'combinationalObject');
INSERT INTO categories VALUES(39,3,'Επαγγέλματα', 'combinationalProfessions');
INSERT INTO categories VALUES(40,3,'Ενέργειες', 'combinationalAction');
INSERT INTO categories VALUES(41,3,'Αλληλουχία Πράξεων', 'combinationalSequence');
