CREATE TABLE IF NOT EXISTS "scores" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"username"	TEXT,
	"time"	TEXT,
	"date"	TEXT,
	"score"	INTEGER,
	"chapter"	TEXT,
	"category"	TEXT
);

CREATE TABLE IF NOT EXISTS "sounds" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"path"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "chapters" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"greekName"	TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS "categories" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"chapterId"	INTEGER NOT NULL,
	"greekName"	TEXT NOT NULL,
	"name"	TEXT,
	FOREIGN KEY("chapterId") REFERENCES "categories"
);

CREATE TABLE IF NOT EXISTS "questions" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "screenTypes" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "screens" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"screenTypeId"	INTEGER NOT NULL,
	"path"	TEXT NOT NULL,
	"name"	TEXT NOT NULL,
	FOREIGN KEY("screenTypeId") REFERENCES "screenTypes"("id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"active"	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "images" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"path"	TEXT NOT NULL
);
